[project]
name = "ds-environment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "El Brewster", email = "167570227+elbi3@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
]

[project.scripts]
ds-environment = "ds_environment:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
