[project]
name = "javabears-sales"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "El Brewster", email = "167570227+elbi3@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.4.0",
    "notebook>=7.6.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
javabears-sales = "javabears_sales:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
